CREATE TABLE company_feedback (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '意见ID',
    user_id BIGINT NOT NULL COMMENT '提交用户ID',
    category VARCHAR(30) NOT NULL COMMENT '意见分类：FEATURE=功能建议，BUG=问题反馈，EXPERIENCE=体验优化，AI=AI建议，OTHER=其他',
    content TEXT NOT NULL COMMENT '意见内容',
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED' COMMENT '处理状态：SUBMITTED=已提交，REVIEWED=已查看，DONE=已处理',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='战狼公司意见收集箱';
